### ISSUE TITLE
Problem in Gaussianmodels

### ISSUE THREAD

**Issue by Yu0xin** [NREL/floris#159]
**Problem**
Learn Floris through the Example you gave in GitHub, but encountered a problem here (the problem is shown in the figure below), how can I solve it?

**Floris Version**
2.2.0

**System Information** 
 win10

![problem](https://user-images.githubusercontent.com/72505662/95337962-01765f80-08e5-11eb-842e-2c4342870f12.PNG)
**Thank you very much!**

**Comment by bayc** [comment]
It seems like your code may be out of sync with the latest available on github. To update the code, I would suggest updating your local references and pulling down the latest version. This can be accomplished with the following commands:
```
git fetch --all
git pull
```
This will pull down the latest code. If you have made any changes locally, you may need to stash those so that the pull can complete. If this is the case, you would want to run `git stash` before the above commands, and then follow the above commands with `git stash pop`.

**Comment by Yu0xin** [comment]
Because I don’t know how to use Git, I directly found the` floris.simulation.wake_velocity.gaussianModels.gaussian_model_base.py `file and deleted `turbine.average_velocity` according to the latest definition in your github.
Very grateful for your help!

**Comment by bayc** [comment]
Glad we got it fixed!
