### ISSUE TITLE
certain fixed power

### ISSUE THREAD

**Issue by tatesnow** [NREL/floris#213]
Hello, I am recently going to do research on power-limited operation of offshore wind farms and would like to know if floris can maintain the wind turbine at a certain fixed power by reducing the speed.

**Comment by Bartdoekemeijer** [comment]
Hi,

Let me paraphrase your question to make sure I understand it correctly. You would like to curtail the turbine's power production to something lower than its rated power, for example, to 2.0 MW for a 5.0 MW wind turbine. Even if the turbine could normally extract much more energy, you will always limit to the <= 2.0 MW, correct? I have shown the power curves below.

One way this is achieved in practice is in a similar manner as turbines are currently curtailed to their rated power production, increasing the blades' pitch angle to prevent the rotor from speeding up once the desired power production is achieved. However, such level of detail is not implemented in FLORIS for a multitude of reasons.

Instead, FLORIS relies on precalculated power and thrust coefficient tables (as a function of wind speed) to model the power and thrust behavior. These tables are fixed for a predefined control strategy. You will have to modify these curves in order to get the desired curtailment. For the power production, this is relatively straight-forward:

```
# Turbine variables
rho = 1.225  # Air density
D = 120.  # Rotor diameter
Ad = 0.25 * np.pi * D**2.  # Rotor swept surface area

# Regular operation power
ws = [...]  # Wind speeds in default power curve table
cp = [...] # Power coefficients in default power curve table
power = 0.5 * rho * ws**3 * Ad * cp  

# Curtailed operation
power_curt = 0.5 * rho * ws**3 * Ad * cp
power_curt[power_curt > 2.0e6] = 2.0e6
cp_curt = power_curt / (0.5 * rho * ws**3 * Ad)
```

![curves_5MW](https://user-images.githubusercontent.com/22119448/123112617-135c4c00-d3fb-11eb-8d13-93b28a4b4466.png)

where `cp_curt` is the curtailed power production that you will feed into your floris input .json file.


Since pitch angles come into play at lower wind speeds, I am not positive if there is an easy way to accurately map the thrust coefficients to this curtailed behavior. I am somewhat in the dark here, so do not follow my advice blindly. One method that comes to mind is simply scaling the thrust coefficients linearly with the power coefficient scaling, something like:
```
ct = [...] # Thrust coefficients in default power curve table
ct_curt = (cp_curt / cp) * ct
```
But I cannot confirm whether this is a reliable nor accurate method for doing this. A better way to do this is by recalculating the look-up tables using NRELs [OpenFAST](https://github.com/OpenFAST/OpenFAST).

**Comment by tatesnow** [comment]
Hello, Bart
Thank you very much for your detailed sharing. I have a clearer understanding of my question from your response.
I am trying to multiply the power curve by the Power limit degree (greater than 0, less than 1) to form a new power curve, and then I am now confused as to how to establish the relationship between power and thrust coefficient for power-limited conditions.

**Comment by Bartdoekemeijer** [comment]
Hi,

Thank you for that clarification. What exactly are you trying to achieve with scaling the power curve by a constant? If you are looking to curtail the turbine to a constant power production, the example I have shown you above would be a more realistic way (closer-to-reality) of achieving that. Or are you trying to keep a certain percentage of power reserve (e.g., only capturing 80% of the available power and keeping 20% in the reserve)?

In principle, depending on your motivation, a linear scaling of the power curve could come from a variety of turbine modifications. For example, a constant reduction in power production could come from a reduction in the blade length (i.e., having a smaller rotor swept area), a decrease in generator efficiency, a change in the blade design, or using a different turbine controller, among others. While all these modifications can have the same effect on the power curve, these have fundamentally different effects on the thrust curve. For example, a decrease in the generator efficiency would decrease your power production but would leave your turbine thrust curve intact. However, a different turbine controller would probably reduce the thrust coefficients, and a different blade design may either decrease or increase your thrust coefficient curves.

Hence, there is no single answer to your question. It essentially depends on how you plan to achieve this reduction in power production. Different choices have different impacts on your thrust coefficient. To get a truly realistic thrust curve, I suggest you implement the changes in the turbine of interest using OpenFAST and extract the thrust and power curves from that simulation environment. Alternatively, you can make some crude assumptions on that the thrust curve scales linearly with the power curve, but I would not rely too much on the outcomes of those simulations.

**Comment by tatesnow** [comment]
Hi, Bart
Thank you very much!  In China, there are frequent incidents of power limitation at wind farms. When the output power of a wind farm exceeds the required load on the grid, the grid will limit the output power of the wind farm to a certain limit, and then the wind farm operator will limit the output power of the wind turbines so that the output power of the wind farm finally meets the grid dispatch requirements. What I want to do is to determine the optimal level of power limitation for each wind turbine in a given incoming flow situation, in order to reduce the total fatigue damage of the wind turbines in the wind farm while meeting the grid dispatch requirements. Therefore, I need to obtain the thrust coefficient curves for different levels of power limitation in order to calculate the wake flow.

**Comment by Bartdoekemeijer** [comment]
I see. There is a broad research interest in this topic, defining it as "active power control (APC)" or "primary/secondary frequency control". There are quite a number of challenges that you will face when addressing this problem, and you might want to consider, including whether FLORIS is the best tool to evaluate all of this.

Namely, when assigning a certain power setpoint to a wind farm:
- How will you distribute the power setpoint among the turbines? Equal everywhere? What if certain turbines cannot achieve that power production? Take a look at this work: https://www.sciencedirect.com/science/article/pii/S240589631730722X that suggests a PID controller to distribute the power production among the turbines.
- How will you curtail the turbines to achieve that assigned power production? Take a look at the work of Jacob Aho, for example, https://ieeexplore.ieee.org/abstract/document/6315180.
- Connecting to all of this: you aim to minimize the fatigue damage to the turbines. That gives you multiple choices. For example, you could minimize the maximum fatigue damage between the turbines, or minimize the average fatigue damage between the wind turbines. These will give you different solutions.

If you really aim to test turbine curtailment and fatigue minimization, you may be better off with a dynamic simulation environment such as NRELs FAST.Farm. That will also provide you turbine structural loads and fatigue damage outputs, whereas FLORIS has no such capabilities currently.

Anyhow, I think this discussion is turning into a general discussion on wind farm active power control and wind turbine curtailment. If you have more questions specifically about FLORIS, or would like to continue this discussion, I kindly ask you to open a new topic on the [FLORIS Discussions](https://github.com/NREL/floris/discussions) page. In the meantime, I am closing this issue.

All the best,
Bart
