### ISSUE TITLE
what is the meaning of wind_veer?

### ISSUE THREAD

**Issue by tatesnow** [NREL/floris#235]
what is the meaning of wind_veer?

**Comment by bayc** [comment]
Wind veer is a variation of wind direction with height. The input variable `wind_veer` in the input json file is used in some of the models to take into account the amount of veer across the rotor, and is defined as the amount of wind direction change over the rotor in degrees. There is currently research going on with FLORIS to further validate the use of veer in the models and its effects on wake steering.

**Comment by Bartdoekemeijer** [comment]
Just as a quick remark: please ask these kind of questions in "Discussions" rather than "Issues". This will make it easier for other users to find answers to the same question later on. It will also help separate the current technical issues with the FLORIS code from explanatory questions and discussions. Thank you!

**Comment by tatesnow** [comment]
@Bartdoekemeijer Thank you very much!
