### ISSUE TITLE
Visualizations of yawed flow dont appear yawed

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#318]
**Bug description**
Making a horizontal plot of a case with turbine yaw doesn't look like the turbine has been yawed

**To Reproduce**
Created this code which runs the example 3 turbine farm all aligned, or all 30 degrees.  Change in yaw is evident in the printed power but not in the visualization
```

import matplotlib.pyplot as plt
import numpy as np

from floris.tools import FlorisInterface
from floris.tools.visualization import visualize_cut_plane

fig, axarr = plt.subplots(2,1,figsize=(10,5))

fi = FlorisInterface("inputs/gch.yaml")
fi.calculate_wake()
print(fi.get_turbine_powers())
horizontal_plane = fi.get_hor_plane(x_resolution=200, y_resolution=100)
visualize_cut_plane(horizontal_plane, ax=axarr[0], title="Aligned")


# Yaw the turbines
fi = FlorisInterface("inputs/gch.yaml")
yaw_angles = 30 * np.ones([1,1,3])
fi.calculate_wake(yaw_angles)
print(fi.get_turbine_powers())
horizontal_plane = fi.get_hor_plane(x_resolution=200, y_resolution=100)
visualize_cut_plane(horizontal_plane, ax=axarr[1], title="Yawed")


plt.show()

# Printed output:
# [[[1691326.48288851  429440.47062303  477388.23077145]]]
# [[[1294346.94921053  730096.98655742  845394.24451798]]]
```

**Expected behavior**
Would expect the lower plot to show wake steering

**Screenshots, if applicable**
![image](https://user-images.githubusercontent.com/6117702/154151238-0a9f3267-b85d-40e9-821a-76663d8d659b.png)

**Floris Version**
v3

**Comment by bayc** [comment]
@paulf81 because of the way FLORIS is reinstantiated for the get_plane calls, the yaw angle information is lost. As such, `yaw_angles` is a variable that can be passed into the get_plane calls, and then the yawed flow should show up in the plots. Do you think this is satisfactory? Again, the thought we have been trying to implement with v3 is that things are more explicitly defined, so that we don't get stuck in situations where things are retained when we don't want them to be.
