### ISSUE TITLE
Different model parameters in config file and paper

### ISSUE THREAD

**Issue by DeeDive** [NREL/floris#65]
Hi there,
I'm currently trying to experiment with model presented in (Gebraad et `al.,` 2016), where Jensen wake model and Jiménez wake deflection model were combined. But I find that parameters shown in the table are different from those in example_input.json? Why? Which one is reliable?

`        "jimenez": {
          "kd": 0.05,
          "ad": 0.0,
          "bd": 0.0
        },
`

![image](https://user-images.githubusercontent.com/42198534/75250170-b8b8dd00-5812-11ea-9927-e4934bffb964.png)

Millions of thanks in advance.
> Gebraad, P.M.O., Teeuwisse, F.W., Wingerden, J.W. van, Fleming, P.A., Ruben, S.D., Marden, J.R., Pao, L.Y., 2016. Wind plant power optimization through yaw control using a parametric model for wake effects—a CFD simulation study. Wind Energy 19, 95–114. https://doi.org/10.1002/we.1822

**Comment by bayc** [comment]
Hello @Tri-Stack ,

The parameters in `example_input.json` are values from previous tunings against LES simulations at the time, so that is why those values differ from those given in the table in the paper. To be candid, those values have not been touched for several years as the Gaussian wake model has been the one in use at NREL. As such, due to the numerous changes and updates to FLORIS from that time, the optimal values have probably shifted from either of those two options. I would suggest to tune to data you have available, if possible. If you don't have data available, we are in the process of putting together a SOWFA library that would have cases you could tune against, but it is not quite ready yet. It will be released soon.

Cheers

**Comment by DeeDiveT** [comment]
Hi @bayc , is there any suggestion on tuning the parameter based on simulation results or recent progress on SOWFA library you mentioned above? 

Thanks a lot.
