### ISSUE TITLE
Bug in get_turbine_ais()

### ISSUE THREAD

**Issue by benoitFoloppe** [NREL/floris#685]
Hello,

Currently the `fi.get_turbine_ais()` function is bugging. 

This is due to a small mistake at line 428 in turbine.py : 

https://github.com/NREL/floris/blob/5e5bb7f4e653621e7a81ff4bcaa27dbc1f759de7/floris/simulation/turbine.py#L428

The call to `_filter_convert` function should be after the `if ix_filter is not None:` condition, consistently with other function in the turbine.py file.

Best,

Benoit

**Comment by benoitFoloppe** [comment]
Hi @rafmudaf,

Here is the example : 

`import numpy as np
from floris.tools import FlorisInterface

yaw_angles = np.zeros((1,1, 2))
fi = FlorisInterface("inputs/gch.yaml")
fi.calculate_wake(yaw_angles=yaw_angles)
print(fi.get_turbine_ais())`

The output error is 

  File "/xxx/floris/examples/02_visualizations.py", line 52, in <module>
    print(fi.get_turbine_ais())
  File "/xxx/floris/tools/floris_interface.py", line 630, in get_turbine_ais
    turbine_ais = axial_induction(
  File "/xxx/floris/simulation/turbine.py", line 439, in axial_induction
    ref_tilt_cp_ct = ref_tilt_cp_ct[:, :, ix_filter]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

**Comment by rafmudaf** [comment]
@benoitFoloppe disregard the previous comment. I wasn't able to reproduce this issue on my end, but it's because I am using the `develop` branch where this bug has already been fixed. See #665.

@paulf81 I think this should be included in a bug-fix release, v3.4.1, since anyone who has installed from pip will not be able to use a few of the functions in FlorisInterface.

**Comment by christiannvaughn** [comment]
@benoitFoloppe bug fixed! See the latest release v3.4.1 from @rafmudaf

**Comment by paulf81** [comment]
Thanks @rafmudaf !
