### ISSUE TITLE
Heterogeneous wind direction and heterogeneous turbulence intensity.

### ISSUE THREAD

**Issue by CaiZhiming-HHU** [NREL/floris#852]
Hello, I recently read a paper: _Design and analysis of a wake model for spatially heterogeneous flow_. This article mainly describes the implementation of heterogeneous flow. I have two questions about it.
1. What is the heterogeneous flow interpolation method? I noticed that the FLORIS-3.5 code uses linear interpolation using **SciPy's LinearNDInterpolator**. However, the paper proposes to use **Delaunay triangulation and Barycentric interpolation**. How can I implement the interpolation method in the paper?implement the interpolation method in the paper?
2. In addition to heterogeneous wind speed, the paper also mentions **heterogeneous wind direction and heterogeneous turbulence intensity**. However, in the code of FLORIS-3.5, I only saw the **heterogeneous wind speed** function implemented (using speed_multipliers under different x,y and z). So how do I achieve **heterogeneous wind direction and heterogeneous turbulence intensity**?

**Comment by CaiZhiming-HHU** [comment]
> Hello, I would like to ask you how to adjust the pitch angle β of the fan in floris and by what parameter. thanks!!!

I think only by modifying the thrust coefficient curve and power coefficient curve can the pitch angle change be realized.

**Comment by misi9170** [comment]
Hi

> > Hello, I would like to ask you how to adjust the pitch angle β of the fan in floris and by what parameter. thanks!!!
> 
> I think only by modifying the thrust coefficient curve and power coefficient curve can the pitch angle change be realized.

@yinghanguan , @CaiZhiming-HHU is correct here---the effect of a change in pitch angle will need to be captured in the turbine power and thrust coefficients. This is already what is done above rated power---the Cp and Ct values decrease above rated, modeling the effect of increasing the blade pitch angle to maintain the rated rotor speed.

**Comment by misi9170** [comment]
@CaiZhiming-HHU , regarding your question:

The current implementation of Floris only support wind speed heterogeneity. If you need wind direction and turbulence intensity heterogeneity, this is available in [Floris v2](https://github.com/NREL/floris/tree/v2).

Support for heterogeneous wind directions and turbulence intensities was not brought over to [Floris v3](https://github.com/NREL/floris/releases/tag/v3.0) (the current version), because the vectorization of much of Floris was difficult to reconcile with wind direction heterogeneity. The upcoming release of [Floris v4](https://github.com/NREL/floris/tree/v4) will also support only wind direction heterogeneity, and we do not current have plans to reimplement wind direction heterogeneity at this time.

See also #803.
