### ISSUE TITLE
Bug report: None Turbulence model returns the wrong values

### ISSUE THREAD

**Issue by Bartdoekemeijer** [NREL/floris#893]
# The 'None' turbulence model is incorrect in its current implementation.

## How to reproduce
The turbulence model is a wake-added turbulence model, which is added on top of the ambient turbulence intensity. Currently, the 'None' turbulence model returns the ambient turbulence values, while it should return zeros.

## Relevant output

The turbulence model should return zeros.

## Floris version
FLORIS v3.6 but it's also in v4:
https://github.com/NREL/floris/blob/6181d78d9c9bd52a3a23f97f6d37ef3ebd84e11e/floris/core/wake_turbulence/none.py#L32C20-L32C44

## System Information
N/A

**Comment by Bartdoekemeijer** [comment]
Sorry for the short bug report. Jasper Kreeft found this while cross-validating wake modeling tools and wanted to flag this.

**Comment by misi9170** [comment]
Thanks @Bartdoekemeijer ! I can see the issue that you are talking about. When running the GCH model (solved using `sequential_solver()`) an atmospheric TI of 0.06, with the `NoneWakeTurbulence` model selected, the `wake_added_turbulence_intensity`, calculated [here](https://github.com/NREL/floris/blob/main/floris/core/solver.py#L220) is 0.06, rather than the expected 0. 

This is a direct result of [this line](https://github.com/NREL/floris/blob/main/floris/core/wake_turbulence/none.py#L32), which appears to be incorrect. Since the TI returned by this model (as well as any other turbulence intensity model) will be added to the ambient TI, this line should simply be changed to `return np.zeros_like(x)`. 

I will check to see if there is anywhere where the turbulence intensity model is being used to represent the "full" turbulence intensity (combined ambient and wake), to ensure that changing this to 0 does not conflict with the usage in other solvers.

**Comment by misi9170** [comment]
Addressed in #894
